### ISSUE TITLE
Zodiac Sign emojis

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#388]
Current emojis cover many variants of zodiac signs.
The Eastern/Chinese/Asian animal zodiac signs are included with several local variants, most of them as full-body and (possibly unified) face-only variants. 
The Western/European zodiac signs are available as symbols and as objects (animals, people, things). There are, however, some more exotic astronomic traditions that would require further emojis.

Japanese Zodiac
------------------

The Japanese zodiac animals should be covered already, but the Dragon :dragon: / :dragon_face:  is sometimes a Seahorse #176 instead.

Celtic Animal Zodiac
----------------------

I found different lists online, have not found a canonical reference yet.

### [What's Your Sign: _Lunar Celtic Animal Zodiac_](http://www.whats-your-sign.com/celtic-animal-signs.html)

| Emoji | Sign | Start date |  
| ---- | ---- | ---- |  
| :deer: | Stag/Deer | December 24 |  
| :cat2: :cat: | Cat | January 21 |  
| :snake: | Snake/Adder | February 18 |  
| :fox_face: | Fox | March 18 |  
| :ox: :cow2: :cow: | Bull/Cow/Cattle | April 15 |  
| #176 | Seahorse | May 13 |  
| (:bird:) | Wren (bird) | June 10 |  
| :horse: :racehorse: | Horse | July 8 |  
| :fish: | Salmon/Fish | August 5 |  
| #94 | Swan | September 2 |  
| :butterfly: | Butterfly | September 30 |  
| :wolf: :dog2: :dog:  | Wolf/Hound | October 28 |  
| #229 | Hawk/Falcon | November 22 |  

### [Astrology of the Ancients: _Celtic Animal Zodiac Signs and Meanings_](http://www.astrologyoftheancients.com/celtic-animal-zodiac-signs/)

| Emoji | Sign | Start date |  
| ---- | ---- | ---- |  
| :dragon: :dragon_face: | Green Dragon | January 21 |  
| #176 | Seahorse | February 18 |  
| #229 | Hawk | March 18 |  
| (:snake:) | Sea Serpent | April 15 |  
| :fox_face: | Fox | May 13 |  
| (:horse: :racehorse:) | White Horse | June 10 |  
| :unicorn: | Unicorn | July 8 |  
| (:fish:) | Rainbow Salmon | August 5 |  
| #94 | White Swan | September 2 |  
| :butterfly: | Butterfly | September 30 |  
| :wolf: :dog2: :dog:  | White Hound | October 28 |  
| (:horse: :racehorse:) | Black Horse | November 25 |  
| :deer: | Stag | December 24 |  

### Tarot.com

[![](https://gfx.tarot.com/images/feeds/infographics/celtic-780x930.png)](https://www.tarot.com/astrology/celtic-signs)

| Emojis | Animals | Tree | Start date |  
| ---- | ---- | ---- | ---- |  
| :eagle:, :deer: | Golden Eagle, White Stag | Birch | December 24 |  
| #210, :dragon: :dragon_face:  | Crane, Green Dragon | Rowan | January 21 |  
| #102, #176, #90 | Seal, Seahorse, Seagull | Ash | February 18 |  
| :bear:, :fox_face:, #229 | Bear, Fox, Hawk | Alder | March 18 |  
| :snake:, :rabbit2: :rabbit:, (:dragon: :dragon_face:) | Adder, Hare, Sea Serpent | Willow | April 15 |  
| :bee:, :owl: | Bee, Owl | Hawthorn | May 13 |  
| (:bird:), #101, :horse: :racehorse: | Wren, Otter, White Horse | Oak | June 10 |  
| :cat2: :cat:, :unicorn: | Cat, Unicorn | Holly | July 8 |  
| #210, :fish: | Crane, Salmon | Hazel | August 5 |  
| :lizard:, :dog2: :dog:, #94 | Lizard, Hound, White Swan | Wine | September 2 |  
| :boar:, :butterfly:, #95 | Boar, Butterfly, Goose | Ivy | September 30 |  
| :wolf: :dog2: :dog:, :owl: | Hound, Owl | Reed | October 28 |  
| #111, :horse: :racehorse:, #208 | Badger, Black Horse, Raven | Elder | November 22 |  

Native American Zodiac
--------------------------

There were so many pre-Columbian tribes and peoples in the Americas that it's unlikely they all shared a single consistent set of zodiac signs, but you will find some like this (obviously North-American) one online:

| Emoji | Sign | Start date |  
| ---- | ---- | ---- |  
| #95 | Goose | December 22 |  
| #101 | Otter | January 20 |  
| :wolf: | Wolf | February 20 |  
| #229 | Falcon | March 20 |  
| #123 | Beaver | April 20 |  
| :deer: | Deer | May 21 |  
| (:bird:) | Woodpecker | June 21 |  
| (:fish:) | Salmon | July 22 |  
| :bear: | Bear | August 22 |  
| #208 | Raven / Crow | September 22 |  
| :snake:  | Snake | October 23 |  
| :owl: | Owl | November 23 |  

These are also referred to as _totems_ or _spirit animals_.

References
------------

* https://www.tarot.com/astrology/best-emojis-for-your-zodiac-sign

Standard References
-------------------

- [Unicode Technical Standard 51 “Unicode Emoji”](http://unicode.org/reports/tr51/) ([beta](http://unicode.org/reports/tr51/proposed.html))
- [How to propose emojis to Unicode](http://unicode.org/emoji/selection.html)
- [Unicode document submission form](http://www.unicode.org/reporting.html)

**Comment by Crissov** [comment]
There are other North American totem animals as well, many of which are already covered:

- [x] Alligator
- [x] Ant
- [ ] Anteater 
- [ ] Antelope
- [ ] Armadillo
- [x] Badger #111 
- [x] Bat
- [x] Bear
- [x] Beaver #123 
- [x] Bee
- [x] Boar/Pig
- [ ] Bobcat (same as Lynx)
- [x] Buffalo
- [x] Bull
- [ ] Bumblebee (unless same as Honey Bee)
- [x] Butterfly
- [x] Camel
- [ ] Caribou (unless same as Deer)
- [x] Cat
- [ ] Cheetah (unless same as Leopard) #89
- [ ] Cougar (unless same as Leopard) #89
- [x] Cow
- [ ] Coyote
- [ ] Cobra (unless same as Snake)
- [x] Crab
- [ ] Crane #210 
- [x] Crocodile (same as Alligator)
- [x] Crow (same as Raven) #208 
- [x] Deer (same as Stag)
- [x] Dog	
- [ ] Dogfish
- [x] Dolphin
- [x] Dove
- [x] Dragon
- [ ] Dragonfly
- [x] Duck
- [x] Eagle
- [x] Elephant
- [x] Elk
- [ ] Falcon (Bird of Prey #229)
- [x] Fish
- [x] Flamingo #92 
- [x] Fox
- [x] Frog
- [ ] Gazelle (perhaps same as Antelope)
- [x] Giraffe
- [x] Goat
- [x] Goose #95 
- [x] Gorilla
- [x] Grasshopper (same as Cricket)
- [x] Grouse (same as Chicken)
- [x] Grizzly (same as Bear)
- [ ] Halibut
- [ ] Hawk #229 
- [ ] Heron/Egret #210 
- [x] Hippopotamus
- [x] Horse
- [ ] Hummingbird
- [ ] Jaguar (unless same as Leopard) #89
- [x] Kangaroo
- [ ] Killer Whale / Orca (unless same as Whale)
- [ ] Kingfisher
- [x] Lion
- [x] Lizard
- [x] Llama
- [ ] Lynx
- [ ] Meerkat
- [ ] Mole
- [ ] Mongoose
- [x] Monkey
- [x] Moose (same as Elk)
- [x] Mouse
- [x] Octopus
- [x] Opossum
- [ ] Ostrich
- [x] Otter
- [x] Owl
- [x] Ox (same as Bull)
- [ ] Panther (unless same as Leopard) #89
- [x] Parrot
- [x] Peacock
- [ ] Pelican #211 
- [x] Penguin
- [ ] Porcupine
- [ ] Prairie Dog
- [ ] Puma (unless same as Leopard) #89 
- [ ] Quail 
- [x] Rabbit
- [x] Raccoon
- [x] Ram
- [x] Rat
- [ ] Raven (same as Crow)
- [x] Rhinoceros
- [ ] Roadrunner
- [x] Rooster
- [ ] Salmon #391 
- [x] Scorpion
- [ ] Seagull #90 
- [ ] Seahorse #176 
- [x] Seal #102 
- [x] Shark
- [x] Skunk #225 
- [x] Snail
- [x] Snake
- [x] Spider
- [x] Squirrel (unless same as Chipmunk) #225 
- [x] Stag (same as Deer)
- [x] Swan #94 
- [x] Tiger
- [ ] Toad (unless same as Frog)
- [x] Turkey
- [x] Turtle
- [x] Unicorn
- [ ] Weasel #97 
- [x] Whale
- [x] Wolf
- [ ] Woodpecker #390 
- [x] Zebra
 
Sources
---------

- http://www.legendsofamerica.com/na-totems.html
- https://www.warpaths2peacepipes.com/native-american-culture/animal-totems.htm

**Comment by Crissov** [comment]
|🇨🇳|👤|🇮🇷|🇻🇳|🇯🇵|🇹🇭|🇰🇿|
|--|--|--|--|--|--|--|
|🐕|🐶|
|🐖|🐷| | |🐗|🐘|🐗|
|🐀|🐭|🐁|
|🐂|🐮|🐄|🐃| | |🐄|
|🐅|🐯|🐆| | | |🐆|
|🐇|🐰| |🐈🐱|
|🐉|🐲|🐊 🐋🐳| | | |🐌 🐺|
|🐍| |
|🐎|🐴|
|🐏| |🐑|🐐| | |🐑|
|🐒|🐵|
|🐓| |🐔| | | |🐔|

|♈️|♉️|♊️|♋️|♌️|♍️|♎️|♏️|♐️|♑️|♒️|♓️|
|--|--|--|--|--|--|--|--|--|--|--|--|
|🐏|🐂|👬 👭|🦀|🦁|👰 👧|⚖|🦂|🏹|🐐|🏺|🐟|
