### ISSUE TITLE
Blackberry Messenger (BBM) emoticons list

### ISSUE THREAD

**Issue by Crissov** [Crissov/unicode-proposals#420]
The RIM Blackberry Messenger (BBM) comes with custom emoticons, many of which are matching standard Unicode emojis. A lot of them are face-based and skin and gender-neutral, where Unicode offers more specific variants. Many hand gestures (with white _gloves_) are shown with a smiley face, where Unicode has them without one.

-  Official documentation: [Emoticons available in BBM](https://help.bbm.com/en/support/solutions/articles/19000060707-emoticons-available-in-bbm)

![](https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/19010549297/original/5KN8kNwzXbVvhJIMZ8q9bPLH49yDLlTWJA.png)
![](https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/19010549320/original/wCAjzPc_62WcDc1593XzF_i4oUqjtARkHQ.png)
![](https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/19010549551/original/nFnhFqNj_v8j82akF0jG3HOnwt1NOJB62w.png?1498664589)
![](https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/19010549409/original/VKvlb5FSgm4amqSGz905JeDAgp4pmxDOEQ.png)
![](https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/19010549419/original/1tb-B7WpcNUlM3jKrj3h-QbWVoXftFlVHw.png)

Conclusion
---------------

- [ ] Goldfish :fish: :tropical_fish:
- [ ] Beetle :bug:
- [ ] Troll #227 
- [ ] Cyclops
- [ ] Pirate #339 
- [ ] Jester
- [ ] Chef
- [ ] Moustache #164 
- [ ] Disguise
- [ ] Hacker / Bandit #298 
- [ ] Sombrero / Mexican #19 
- [ ] Oncoming Truck
- [ ] Steering Wheel #189
- [ ] Maraca, Rattle
- [ ] Coffee Mug (not Cup) 
- [ ] Tea Cup (with Tea Bag) (#157) 
- [ ] Multiple Presents
- [ ] Queen Crown, King Crown 
- [ ] Tornado
- [ ] Horseshoe #218 
- [ ] Barbell, Dumbbell #335 
- [ ] Hippie
- [ ] Emo
- [ ] High Five
- [ ] Nail-Biting Face (similar to #145 #146)
- [ ] Nose-Picking Face #369 
- [ ] Food-Stuffing Face
- [ ] Beat-up / Bruised Face
- [ ] Bags under Eyes Face
- [ ] Secret Telling / Whispering Face
- [ ] Tongue-Tied Face (#146) 
- [ ] Grimacing Face with Fingers
- [ ] Tongue-in-Cheek Face
- [ ] Too-Loud Face
- [ ] Headache Face
- [ ] Steaming Face
- [ ] Head-Scratching Face
- [ ] Arms-Crossed Face / Person
- [ ] Wavy Mouth Face `:-S`
- [ ] Touched / Happy Crying Face `:')`
- [ ] Sceptical or Thinking Face distinct from :thinking: 

Some could possibly be represented by sequences sufficiently:

- [ ] Talk-to-the-Hand Face :hand: 
- [ ] Hands-up Face :hand: :hand: 
- [ ] Too-Late Face :watch: 
- [ ] Boxing Face :boxing_glove: 
- [ ] Thumbs-Down Faces :-1:, :-1::-1:
- [ ] Pretty Face :lipstick: 
- [ ] Reading Face :book: :eyeglasses: 
- [ ] Not Listening Face :point_right: :point_left: 
- [ ] Phew Face
- [ ] Cannot-Look Faces
- [ ] Rocker Face :metal: :dark_sunglasses:  
- [ ] DJ Face :headphones: 
- [ ] Idea Face :bulb: 
- [ ] Hi Face :wave: 
- [ ] Hippie Face :v:
- [ ] One-Moment Face :point_up: 
- [ ] On the Phone Face :point_up: :telephone_receiver: 
- [ ] High-Fiving Face :hand: 
- [ ] Clapping Face :clap: 
- [ ] Whistling Face :kissing: :musical_note:
